name: "ResNet20_CIFAR_Full"
logging:
  out_dir: log/cifar
model:
  type: CIFAR10
  operator: COSCONV2D
  orders: [3, [3, 3], [3, 3], [2, 2]]
training:
  milestones: [91, 137]
  lr: 0.1
pl:
  max_steps: 32000
  val_every: 20
